#!/usr/bin/env bash

pbscript="/Users/ccorwin/Google Drive/Documents/pasteboard.sh"

touch "${pbscript}"

pbpaste > "${pbscript}"

highlight -O rtf -t 2 -K 11 -k 'Source Code Pro' --syntax 'Bash' "${pbscript}" | pbcopy

echo -n "Enter gist filename and press [ENTER]: "

read gistfilename

if [[ -n "${gistfilename/[ ]*\n/}" ]]
then
  #execute if the the variable is not empty and contains non space characters
  echo "New filename is: ${gistfilename}";
  gist --filename "${gistfilename}.sh" --open "${pbscript}"
else
  echo "Using default (foo) filename.";
  #execute if the variable is empty or contains only spaces
  gist --type sh --open "${pbscript}"
fi