#!/bin/bash


touch '/Users/ccorwin/Google Drive/Documents/pasteboard.js'

pbpaste > '/Users/ccorwin/Google Drive/Documents/pasteboard.js'


highlight -O rtf -t 2 -K 11 -k 'Source Code Pro' --syntax 'js' '/Users/ccorwin/Google Drive/Documents/pasteboard.js' | pbcopy

gist --type js --open '/Users/ccorwin/Google Drive/Documents/pasteboard.js'
