#!/bin/bash

# Takes a in.mov file on the desktop and outputs an animated gif at ~/Dropbox/Screenshots/out.gif


ffmpeg -i ~/Desktop/in.mov -s 960x600 -pix_fmt rgb24 -r 10 -f gif - | gifsicle --optimize=4 --delay=10 > ~/Dropbox/Screenshots/out.gif
# ffmpeg -i ~/Desktop/in.mov -s 942x782 -pix_fmt rgb24  -f gif - | gifsicle --optimize=4 --delay=3 > ~/Dropbox/Screenshots/out.gif
# ffmpeg -i ~/Desktop/in.mov -s 942x782 -pix_fmt rgb24 -r 30 -f gif - | gifsicle --optimize=4 --delay=3 > ~/Dropbox/Screenshots/out.gif
